### var

@json = application/json
@localHost = http://localhost:1899
@devHost = https://gai.co.id/gai-ai-service
@host = {{localHost}}
@apiKey = eb7d28cc-40cd-4024-9171-09293c588bdb
@ownerToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnbnVzYSIsImlkIjoiMDFKNkhXODI0WDlDREQ5Rkg2NTRWNFNFUFciLCJyb2xlIjpbIkFETUlOIl0sImF1dGgiOiJPV05FUiIsImNvZGUiOiJyb290IiwiZXhwIjoxNzI2OTAxMzc1fQ.c7mPphsgeFkZZTjEWrC2nQahqxx_93_-l_34CBL6nxw
@partnerToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJib3h5IiwiaWQiOiIwMUo5TkhWVEhGVkUzM0pSQ1FDOUsyMTBTOSIsInJvbGUiOlsiQURNSU4iXSwiYXV0aCI6IlBBUlRORVIiLCJjb2RlIjoiYm94IiwiZXhwIjoxNzI5MzE3NjI1fQ.6aAWj8NWu_iCDB33lEDj_LbBj66ImZhBbmGWQKg7YIk
@clientToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZW1weSIsImlkIjoiMDFKQTJRWUQ0SzkwM1ZOOE5CQVJCMEMxMk4iLCJyb2xlIjpbIkFETUlOIl0sImF1dGgiOiJDTElFTlQiLCJjb2RlIjoidG1wIiwiZXhwIjoxNzI5OTE4Mjk2fQ.yaMb3RwCHutP9YtNF-n3OyrEnB6FuYnWZS2MHVO5EnU
@token = {{clientToken}}


### test ==================================================================================================

GET {{host}}/v1/test HTTP/1.1

###

GET {{host}}/v1/database/test HTTP/1.1
authorization: {{token}}

###

POST {{host}}/v1/database/test/init_db/bxy HTTP/1.1
authorization: {{token}}


### auth ==================================================================================================

### login owner

POST {{host}}/v1/auth/login HTTP/1.1
Accept: {{json}}
content-type: {{json}}

{
  "username": "gnusa",
  "password": "123456"
}

### login partner

POST {{host}}/v1/auth/login HTTP/1.1
Accept: {{json}}
content-type: {{json}}

{
  "username": "boxy",
  "password": "123456"
}

### login client

POST {{host}}/v1/auth/login HTTP/1.1
Accept: {{json}}
content-type: {{json}}

{
  "username": "tempy",
  "password": "123456"
}


### SIMULATION ###
### new chat
POST {{host}}/v1/chat/simulation HTTP/1.1
content-type: {{json}}
authorization: {{token}}

{
  "question": "seperti apa SOP TPTKP?",
  "collection_name": "01JBDYG3H612C8XV1SS9T0BEDH"
}